// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookmarks.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addToBookmarks = `-- name: AddToBookmarks :one
INSERT INTO bookmarks (id, user_id, feed_id, title, url, description, published_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id, feed_id, url) DO UPDATE SET updated_at = EXCLUDED.updated_at
RETURNING id, user_id, feed_id, title, url, description, published_at, created_at, updated_at
`

type AddToBookmarksParams struct {
	ID          uuid.UUID      `json:"id"`
	UserID      string         `json:"user_id"`
	FeedID      uuid.UUID      `json:"feed_id"`
	Title       string         `json:"title"`
	Url         string         `json:"url"`
	Description sql.NullString `json:"description"`
	PublishedAt time.Time      `json:"published_at"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) AddToBookmarks(ctx context.Context, arg AddToBookmarksParams) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, addToBookmarks,
		arg.ID,
		arg.UserID,
		arg.FeedID,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.PublishedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBookmark = `-- name: DeleteBookmark :one
DELETE FROM bookmarks
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, feed_id, title, url, description, published_at, created_at, updated_at
`

type DeleteBookmarkParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"user_id"`
}

func (q *Queries) DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, deleteBookmark, arg.ID, arg.UserID)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookmarksByUser = `-- name: GetBookmarksByUser :many
SELECT 
    b.id,
    b.title,
    b.url,
    b.description,
    b.published_at,
    b.created_at,
    b.updated_at,
    f.id AS feed_id,
    f.name AS feed_name,
    f.url AS feed_url
FROM bookmarks b
LEFT JOIN feeds f ON b.feed_id = f.id
WHERE b.user_id = $1
ORDER BY b.published_at DESC
`

type GetBookmarksByUserRow struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Url         string         `json:"url"`
	Description sql.NullString `json:"description"`
	PublishedAt time.Time      `json:"published_at"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	FeedID      uuid.NullUUID  `json:"feed_id"`
	FeedName    sql.NullString `json:"feed_name"`
	FeedUrl     sql.NullString `json:"feed_url"`
}

func (q *Queries) GetBookmarksByUser(ctx context.Context, userID string) ([]GetBookmarksByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getBookmarksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBookmarksByUserRow{}
	for rows.Next() {
		var i GetBookmarksByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeedID,
			&i.FeedName,
			&i.FeedUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
