// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed_follows.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const followFeed = `-- name: FollowFeed :one
INSERT INTO feed_follows (id, user_id, feed_id, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, feed_id, user_id, created_at
`

type FollowFeedParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    string    `json:"user_id"`
	FeedID    uuid.UUID `json:"feed_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) FollowFeed(ctx context.Context, arg FollowFeedParams) (FeedFollow, error) {
	row := q.db.QueryRowContext(ctx, followFeed,
		arg.ID,
		arg.UserID,
		arg.FeedID,
		arg.CreatedAt,
	)
	var i FeedFollow
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getFollowedFeedsByUser = `-- name: GetFollowedFeedsByUser :many
SELECT feeds.id, feeds.name, feeds.url, feeds.category, feeds.created_at, feeds.updated_at, feeds.last_fetched_at, feeds.feed_followers_count FROM feed_follows
LEFT JOIN feeds ON feed_follows.feed_id = feeds.id
WHERE user_id = $1
ORDER BY feed_follows.created_at DESC
`

type GetFollowedFeedsByUserRow struct {
	ID                 uuid.NullUUID  `json:"id"`
	Name               sql.NullString `json:"name"`
	Url                sql.NullString `json:"url"`
	Category           sql.NullString `json:"category"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
	LastFetchedAt      sql.NullTime   `json:"last_fetched_at"`
	FeedFollowersCount sql.NullInt32  `json:"feed_followers_count"`
}

func (q *Queries) GetFollowedFeedsByUser(ctx context.Context, userID string) ([]GetFollowedFeedsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowedFeedsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFollowedFeedsByUserRow{}
	for rows.Next() {
		var i GetFollowedFeedsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastFetchedAt,
			&i.FeedFollowersCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowFeed = `-- name: UnfollowFeed :one
DELETE FROM feed_follows
WHERE user_id = $1 AND feed_id = $2
RETURNING id, feed_id, user_id, created_at
`

type UnfollowFeedParams struct {
	UserID string    `json:"user_id"`
	FeedID uuid.UUID `json:"feed_id"`
}

func (q *Queries) UnfollowFeed(ctx context.Context, arg UnfollowFeedParams) (FeedFollow, error) {
	row := q.db.QueryRowContext(ctx, unfollowFeed, arg.UserID, arg.FeedID)
	var i FeedFollow
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
