// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feeds.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds(id, name, url, category, created_at, updated_at)
VALUES(?, ?, ?, ?, ?, ?)
RETURNING id, name, url, category, created_at, updated_at
`

type CreateFeedParams struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Url       string         `json:"url"`
	Category  sql.NullString `json:"category"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Category,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const feedExists = `-- name: FeedExists :one
SELECT EXISTS(
    SELECT 1
    FROM feeds
    WHERE url = ?
)
`

func (q *Queries) FeedExists(ctx context.Context, url string) (bool, error) {
	row := q.db.QueryRowContext(ctx, feedExists, url)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAllFeeds = `-- name: GetAllFeeds :many
SELECT id, name, url, category, created_at, updated_at FROM feeds
`

func (q *Queries) GetAllFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getAllFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
