// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Feed struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Url       string         `json:"url"`
	Category  sql.NullString `json:"category"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
