// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addPostsToDatabase = `-- name: AddPostsToDatabase :many
INSERT INTO posts (id, feed_id, title, url, description, published_at, created_at, updated_at) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (url) DO NOTHING
RETURNING id, feed_id, title, url, description, published_at, created_at, updated_at
`

type AddPostsToDatabaseParams struct {
	ID          uuid.UUID      `json:"id"`
	FeedID      uuid.UUID      `json:"feed_id"`
	Title       string         `json:"title"`
	Url         string         `json:"url"`
	Description sql.NullString `json:"description"`
	PublishedAt time.Time      `json:"published_at"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) AddPostsToDatabase(ctx context.Context, arg AddPostsToDatabaseParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, addPostsToDatabase,
		arg.ID,
		arg.FeedID,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.PublishedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteStalePosts = `-- name: DeleteStalePosts :exec
DELETE FROM posts
WHERE published_at < NOW() - INTERVAL '7 days'
`

func (q *Queries) DeleteStalePosts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteStalePosts)
	return err
}

const getPostsByFeed = `-- name: GetPostsByFeed :many
SELECT 
    f.id AS feed_id,
    f.name AS feed_name,
    f.url AS feed_url,
    p.id AS post_id,
    p.title AS post_title,
    p.url AS post_url,
    p.description AS post_description,
    p.published_at AS post_published_at,
    p.created_at AS post_created_at,
    p.updated_at AS post_updated_at
FROM feeds f
JOIN posts p ON p.feed_id = f.id
ORDER BY f.name, p.published_at DESC
`

type GetPostsByFeedRow struct {
	FeedID          uuid.UUID      `json:"feed_id"`
	FeedName        string         `json:"feed_name"`
	FeedUrl         string         `json:"feed_url"`
	PostID          uuid.UUID      `json:"post_id"`
	PostTitle       string         `json:"post_title"`
	PostUrl         string         `json:"post_url"`
	PostDescription sql.NullString `json:"post_description"`
	PostPublishedAt time.Time      `json:"post_published_at"`
	PostCreatedAt   time.Time      `json:"post_created_at"`
	PostUpdatedAt   time.Time      `json:"post_updated_at"`
}

func (q *Queries) GetPostsByFeed(ctx context.Context) ([]GetPostsByFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByFeed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostsByFeedRow{}
	for rows.Next() {
		var i GetPostsByFeedRow
		if err := rows.Scan(
			&i.FeedID,
			&i.FeedName,
			&i.FeedUrl,
			&i.PostID,
			&i.PostTitle,
			&i.PostUrl,
			&i.PostDescription,
			&i.PostPublishedAt,
			&i.PostCreatedAt,
			&i.PostUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsFromFollowedFeeds = `-- name: GetPostsFromFollowedFeeds :many
SELECT 
    f.id AS feed_id,
    f.name AS feed_name,
    f.url AS feed_url,
    p.id AS post_id,
    p.title AS post_title,
    p.url AS post_url,
    p.description AS post_description,
    p.published_at AS post_published_at,
    p.created_at AS post_created_at,
    p.updated_at AS post_updated_at
FROM feeds f
JOIN posts p ON p.feed_id = f.id
JOIN feed_follows fo ON fo.feed_id = f.id
WHERE fo.user_id = $1
ORDER BY f.name, p.published_at DESC
`

type GetPostsFromFollowedFeedsRow struct {
	FeedID          uuid.UUID      `json:"feed_id"`
	FeedName        string         `json:"feed_name"`
	FeedUrl         string         `json:"feed_url"`
	PostID          uuid.UUID      `json:"post_id"`
	PostTitle       string         `json:"post_title"`
	PostUrl         string         `json:"post_url"`
	PostDescription sql.NullString `json:"post_description"`
	PostPublishedAt time.Time      `json:"post_published_at"`
	PostCreatedAt   time.Time      `json:"post_created_at"`
	PostUpdatedAt   time.Time      `json:"post_updated_at"`
}

func (q *Queries) GetPostsFromFollowedFeeds(ctx context.Context, userID string) ([]GetPostsFromFollowedFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsFromFollowedFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostsFromFollowedFeedsRow{}
	for rows.Next() {
		var i GetPostsFromFollowedFeedsRow
		if err := rows.Scan(
			&i.FeedID,
			&i.FeedName,
			&i.FeedUrl,
			&i.PostID,
			&i.PostTitle,
			&i.PostUrl,
			&i.PostDescription,
			&i.PostPublishedAt,
			&i.PostCreatedAt,
			&i.PostUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
