// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const addPostsToDatabase = `-- name: AddPostsToDatabase :many
INSERT INTO posts (id, feed_id, title, url, description, published_at, created_at, updated_at) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (url) DO NOTHING
RETURNING id, feed_id, title, url, description, published_at, created_at, updated_at
`

type AddPostsToDatabaseParams struct {
	ID          uuid.UUID      `json:"id"`
	FeedID      uuid.UUID      `json:"feed_id"`
	Title       string         `json:"title"`
	Url         string         `json:"url"`
	Description sql.NullString `json:"description"`
	PublishedAt time.Time      `json:"published_at"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) AddPostsToDatabase(ctx context.Context, arg AddPostsToDatabaseParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, addPostsToDatabase,
		arg.ID,
		arg.FeedID,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.PublishedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsByFeed = `-- name: GetPostsByFeed :many
SELECT 
    f.id AS feed_id,
    f.name AS feed_name,
    f.url AS feed_url,
    json_agg(
        json_build_object(
            'id', p.id,
            'title', p.title,
            'url', p.url,
            'description', p.description,
            'published_at', p.published_at,
            'created_at', p.created_at,
            'updated_at', p.updated_at
        ) ORDER BY p.published_at DESC
    ) AS posts
FROM feeds f
JOIN posts p ON p.feed_id = f.id
GROUP BY f.id, f.name, f.url
ORDER BY f.name
`

type GetPostsByFeedRow struct {
	FeedID   uuid.UUID       `json:"feed_id"`
	FeedName string          `json:"feed_name"`
	FeedUrl  string          `json:"feed_url"`
	Posts    json.RawMessage `json:"posts"`
}

func (q *Queries) GetPostsByFeed(ctx context.Context) ([]GetPostsByFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByFeed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostsByFeedRow{}
	for rows.Next() {
		var i GetPostsByFeedRow
		if err := rows.Scan(
			&i.FeedID,
			&i.FeedName,
			&i.FeedUrl,
			&i.Posts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
