// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	FeedExists(ctx context.Context, url string) (bool, error)
	GetAllFeeds(ctx context.Context) ([]Feed, error)
}

var _ Querier = (*Queries)(nil)
