// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddPostsToDatabase(ctx context.Context, arg AddPostsToDatabaseParams) ([]Post, error)
	AddUserToDatabase(ctx context.Context, arg AddUserToDatabaseParams) (User, error)
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	DecrementFeedFollowerCount(ctx context.Context, id uuid.UUID) (Feed, error)
	FeedExists(ctx context.Context, url string) (bool, error)
	FollowFeed(ctx context.Context, arg FollowFeedParams) (FeedFollow, error)
	GetAllFeeds(ctx context.Context) ([]Feed, error)
	GetFeedstoFetch(ctx context.Context, limit int32) ([]Feed, error)
	GetFollowedFeedsByUser(ctx context.Context, userID string) ([]GetFollowedFeedsByUserRow, error)
	GetPostsByFeed(ctx context.Context) ([]GetPostsByFeedRow, error)
	IncrementFeedFollowerCount(ctx context.Context, id uuid.UUID) (Feed, error)
	MarkFeedAsFetched(ctx context.Context, id uuid.UUID) (Feed, error)
	UnfollowFeed(ctx context.Context, arg UnfollowFeedParams) (FeedFollow, error)
}

var _ Querier = (*Queries)(nil)
