// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"
)

const addUserToDatabase = `-- name: AddUserToDatabase :one
INSERT INTO users(id, email, created_at, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (email) DO NOTHING
RETURNING id, created_at, updated_at, email
`

type AddUserToDatabaseParams struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) AddUserToDatabase(ctx context.Context, arg AddUserToDatabaseParams) (User, error) {
	row := q.db.QueryRowContext(ctx, addUserToDatabase,
		arg.ID,
		arg.Email,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}
